### PR TITLE
Fix b64_ntop test for glibc and add compat-b64_ntop.c

### PR DESCRIPTION
**Pull request by Duncaen**

### CODE REVIEW

**Comment by kristapsdz** [comment]
Sorry for having this merge be a little ugly---all of this comes from CVS, and the merge script has changed a little.

**Comment by kristapsdz** [comment]
I think I have everything checked in here, but the commit log is all messy.  Can you double-check that this does what you want?  If so, I'll version it and close the request.

**Comment by Duncaen** [comment]
On the glibc system:
```
b64_ntop: yes (with -lresolv)
```

On the musl system:
```
b64_ntop: no
```

But I forgot to add a prototype for the `b64_ntop` function to `config.h` if its not available.

**Comment by kristapsdz** [comment]
Does musl actually provide it?  Don't worry about the prototypes---I'll do that now.

**Comment by Duncaen** [comment]
Thanks, its correct, musl doesn't provide `b64_ntop`.

**Comment by kristapsdz** [comment]
Thank you!  And thank you also for getting this all up to speed.  I'm going to tweak the b64 implementation so that it compiles clean, will get the prototypes in, then version up.

**Comment by kristapsdz** [comment]
Done and versioned, thank you!

**Pull request closed without merging**
