### PR TITLE
Test for warnc in err.h

### PR DESCRIPTION
**Pull request by The-King-of-Toasters**

### CODE REVIEW

**Comment by kristapsdz** [comment]
Two things before I can merge this: first, which implementation has warnx and so on but not warnc?  Second, you'll need to provide the compatibility function for warnc in compat_err.c and the prototypes in configure.in.

**Comment by The-King-of-Toasters** [comment]
> Which implementation has warnx and so on but not warnc?

[glibc](https://sourceware.org/git/?p=glibc.git;a=blob;f=include/err.h;h=b9b7516287b7ae003b3c72b8a10554c1795e6fc9;hb=HEAD)

> Second, you'll need to provide the compatibility function for warnc in compat_err.c and the prototypes in configure.in.

Will do.

**Comment by The-King-of-Toasters** [comment]
note that glibc has their own special snowflake clones called `error` and `error_at_line`, but I'm definitely not making wrappers around them.

**Comment by The-King-of-Toasters** [comment]
Ok, how's this?

**Comment by kristapsdz** [comment]
Your patch redefined vwarn in *configure.in*.  What I did in the last commit was grab all sources from lib/libc/gen and use them directly, including the `verr()` style functions.  I then added all of these and also added to the regression test.  Does this look good to you?  If so, I'll add the version notes, document what the test looks for, and tag it.

**Comment by The-King-of-Toasters** [comment]
Doh! Good catch. Everything looks good, but lemme check on my systems.

**Comment by The-King-of-Toasters** [comment]
Here's what I got:

- OmniOS CE -- no (no errc)
- OpenBSD 6.8 -- yes
- Arch Linux w/ glibc 2.32 -- no (no errc)
- Arch Linux w/ musl 1.2.1 -- no (no errc)

Looks good.

**Pull request closed without merging**
